### ISSUE TITLE
Documentation shortcut doesn't work

### ISSUE THREAD

**Issue by ntoshev** [yunabe/tslab#45] opened 2021-01-03 11:14 UTC
Autocomplete works, but I wish I could see documentation of a function with `Shift+Tab`. Is this something that can be configured, or is it simply not implemented yet?

**Comment by yunabe** [comment] 2021-01-04 02:53
Could you share the information about your environment?

In my environment (Mac/Linux), it works both in Jupyter notebook and JupyterLab. Does `Shift-Tab` work with Python kernel in your environment?

**Comment by yunabe** [comment] 2021-03-10 11:55
Let me close this because I can not reproduce it and I don't see any additional information.
Feel free to reopen it with additional information if you can still reproduce it.

**Closed by yunabe** 2021-03-10 11:55 UTC
